# -*- coding: utf-8 -*-
"""GUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13jmjNwJSi8az0MFmxemSkU8k0MdUO65B
"""

from google.colab import files

# Pick and upload your ZIP file from your computer
uploaded = files.upload()

!unzip flask_diabetes_ui_colab.zip -d flask_diabetes_ui_colab

# Commented out IPython magic to ensure Python compatibility.
# %cd flask_diabetes_ui_colab

!ls

!pip install flask pyngrok

uploaded = files.upload()  # choose your model + scaler files
!mv diabetes_model.pkl models/
!mv diabetes_scaler.pkl models/

# install pyngrok (if not installed)
!pip install pyngrok flask

# hide token prompt (safer) and set token
from getpass import getpass
token = getpass("359rxhc0dQgTqwU575C5nfQZmT8_6WZ7q9Dfcrj9mb2P4hdBQ")   # paste token when prompted

from pyngrok import ngrok, conf
ngrok.set_auth_token(token)   # stores token in ~/.ngrok2/ngrok.yml

# start tunnel and print url
public_url = ngrok.connect(8501)
print("Public URL:", public_url)

!python app.py &